package com.example.parkkar.data.model

import com.example.parkkar.model.OpeningTime
import com.example.parkkar.model.PriceInfo
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ThaneRoot(
    @SerialName("?xml") val xmlVersion: String? = null, // Optional field, can be ignored
    @SerialName("parking_data")
    val parkingData: ThaneParkingDataContainer?
)

@Serializable
data class ThaneParkingDataContainer(
    @SerialName("parking_location")
    val parkingLocations: List<ThaneParkingLocationRaw>?
)

@Serializable
data class ThaneParkingLocationRaw(
    val name: String?,
    val address: String?,
    val latitude: Double?,
    val longitude: Double?,
    @SerialName("two_wheeler_parking")
    val twoWheelerCapacity: Int?,
    @SerialName("four_wheeler_parking")
    val fourWheelerCapacity: Int?,
    val prices: List<PriceInfo>?,
    val openingTimes: List<OpeningTime>?,
    @SerialName("CoverageType")
    val coverageType: String?
    // id is missing, will be generated by mapper
)
